### ISSUE TITLE
How can I update this?

### ISSUE THREAD

**Issue by username-pass** [MenschenToaster/DeathShot#1]
I understand that you may not want to spend time supporting this mod, so I am asking how can I update the mod to future versions. I want to learn how to make a mod, but I would like to start small with updating, because it is not making a full mod from scratch. Is this possible? Thank you.

**Comment by davidmayr** [comment]
That doesn't work like that. I can't tell you how you should update a mod to future versions... I don't know what Minecraft will change in the future. This mod(being a fabric mod) will most likely not need any updates in the near future unless Minecraft either reworks the screenshot stuff or intermediary mappings get changed from the fabric team.

I think you should start from scratch. If you don't know Java yet, learn Java first(without it, you won't achieve anything). 

There are many tutorials online for learning java or developing a mod. But this mod probably won't need updates, nor will you achieve anything in learning how to code a mod by just changing the code of others a bit. Mod development can get pretty hard, and such a simple mod will maybe show you how to do a basic mixin and that's it(it's literally two classes). This mod is as basic as it can get.

**Comment by davidmayr** [comment]
I think this can be closed now.
